services:
  portainer:
    image: portainer/portainer-ce:2.9.3
    container_name: portainer
    restart: always
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - 8000:8000
      - 9443:9443

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: "opc"
      POSTGRES_USER: "opc"
      POSTGRES_PASSWORD: "opc"
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Asia/Jakarta"
    volumes:
      - posgres-var-lib-postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    environment:
      TZ: "Asia/Jakarta"
    ports:
      - 8080:8080

  filebrowser:
    image: filebrowser/filebrowser:v2
    container_name: filebrowser
    restart: always
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - ${HOME}/docker-data/filebrowser/filebrowser.db:/filebrowser.db 
      - ${HOME}/docker-data/filebrowser/.filebrowser.json:/.filebrowser.json
      - ${HOME}/docker-data:/srv
    ports:
      - 8081:80

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    restart: always
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - ${HOME}/docker-data/prometheus/etc/prometheus:/etc/prometheus
      - prometheus-prometheus:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:10.0.2
    container_name: grafana
    restart: always
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - grafana-var-lib-grafana:/var/lib/grafana
      - grafana-etc-grafana:/etc/grafana
      - grafana-var-log-grafana:/var/log/grafana
      - ${HOME}/docker-data/grafana_bg:/usr/share/grafana/public/img/bg # Requested by Taufik
    ports:
      - 3000:3000

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 * * * *"

  plantsense:
    image: protanjung/plantsense:latest
    container_name: plantsense
    restart: always
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - ${HOME}/docker-data/plantsense/root/plantsense-data:/root/plantsense-data
      - ${HOME}/docker-data/data_export:/root/plantsense-data/export #Requested by Pandu
    ports:
      - 5000:5000
      - 5001:5001
      - 8000:8000

  ai:
    image: messier12/pjb-ai:latest
    container_name: ai
    restart: always
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - ${HOME}/docker-data/ai_reports:/server/reports # Requested by Dion
      - ${HOME}/docker-data/ai_models:/server/saved_models # Requested by Dion

volumes:
  portainer-data:
  grafana-var-lib-grafana:
  grafana-etc-grafana:
  grafana-var-log-grafana:
  prometheus-prometheus:
  posgres-var-lib-postgresql-data: